### ISSUE TITLE
Read fixture template from disk into memory

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/fs-fixture-builder#6]
Read a template directory into memory in a fixture, modify it in-memory, then emit into a new temp directory.

Proposed API:

```typescript
const fixture = fsFixtureBuilder.project('my-fixture');

// Call `.readFrom()` to recursively read a real filesystem directory into the virtual fixture
fixture.readFrom('test/fixtures/root-boilerplate');

// Can be called on virtual subdirectories, too
fixture.dir('src').readFrom('test/fixtures/src-template');

// Alternative to calling `.readFrom` directly on a project or subdirectory: call `.add` and pass an array read from `fsFixtureBuilder.readFilesFrom`
fixture.add(...fsFixtureBuilder.readFilesFrom('test/fixtures/root-boilerplate'));

fixture.addJsonFile('tsconfig.json', {
  ...fixture.readJsonFile('tsconfig.json') // <-- add `read` variants to pull JSON or text out of the virtual set of files, to allow patching them
});
```

Will need a bit more logic in `addFile` and `addJsonFile` to detect duplicates in the internal `files` array, to allow overwriting/updating file contents.

Instead of `.ingest`, how about `readFrom`?  We already have `.write()` and `.rm()` which interact with the real FS.  So `read` feels intuitive, but `readFrom` makes it clear we're reading from a different directory.

**Comment by cspotcode** [comment]
I should see if I can reuse logic from #4 here, maybe tweak #4 so that it uses this API under the hood?

**Comment by Gerrit0** [comment]
I like `readFrom`, we might want to use `getJsonFile` / `getFile` instead of `readJsonFile` to avoid implying a parallel function to `readFrom` that doesn't exist.

**Comment by cspotcode** [comment]
Good point, `get` and `add` match interfaces of `Set` and `Map` for in-memory stuff, `read` and `write` match FS API for stuff that touches the filesystem.
