### ISSUE TITLE
Possible issue: `get content()` on JsonFile means it's read-only, but type `File` declares `content` as writable

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/fs-fixture-builder#8]
I found this when trying to
```typescript
const file = {
  path: 'foo.txt',
  stuff: ''.
  get content() {
    return this.stuff + whatever;
  }
};
fixture.add(file);
file.stuff += 'append a bunch onto it before emit';

...

fixture.write();
```

Maybe this is just a case of me doing the wrong thing, but on the other hand, the `JsonFile` implementation does the same thing.

**Comment by Gerrit0** [comment]
You're right - we should probably change the internal signature so that `content` is treated as readonly by the fixture builder.
